module.exports = {
  SEMI_COLON_REGEX: /^;/,
  NUMBER_REGEX: /^\d+/,
  WHITESPACE_REGEX: /^\s+/,
  STRING_DQ_REGEX: /^"[^"]*"/,
  STRING_SQ_REGEX: /^'[^']*'/,
  SL_COMMENT_REGEX: /^\/\/.*/,
  OPEN_CURLY_BRACE_REGEX: /^\{/,
  CLOSE_CURLY_BRACE_REGEX: /^\}/,
  OPEN_PARENTHESIS_REGEX: /^\(/,
  CLOSE_PARENTHESIS_REGEX: /^\)/,
  ADDITIVE_OPERATOR_REGEX: /^[+\-]/,
  ML_COMMENT_REGEX: /^\/\*[\s\S]*?\*\//,
  MULTIPLICATIVE_OPERATOR_REGEX: /^[*\/]/,
}