module.exports = {
  NUMBER: 'NUMBER',
  STRING: 'STRING',
  SEMI_COLON: ';',
  WHITESPACE: null,
  SL_COMMENT: null,
  ML_COMMENT: null,
  OPEN_PARENTHESIS: '(',
  CLOSE_PARENTHESIS: ')',
  OPEN_CURLY_BRACE: '{',
  CLOSE_CURLY_BRACE: '}',
  IDENTIFIER: 'IDENTIFIER',
  SIMPLE_ASSIGN: 'SIMPLE_ASSIGN',
  COMPLEX_ASSIGN: 'COMPLEX_ASSIGN',
  ADDITIVE_OPERATOR: 'ADDITIVE_OPERATOR',
  MULTIPLICATIVE_OPERATOR: 'MULTIPLICATIVE_OPERATOR'
}