module.exports = {
  PROGRAM: 'Program',
  Identifier: 'Identifier',
  IfStatement: 'IfStatement',
  STRING_LITERAL: 'StringLiteral',
  NUMERIC_LITERAL: 'NumericLiteral',
  BLOCK_STATEMENT: 'BlockStatement',
  EMPTY_STATEMENT: 'EmptyStatement',
  BINARY_EXPRESSION: 'BinaryExpression',
  VariableStatement: 'VariableStatement',
  AdditiveExpression: 'AdditiveExpression',
  VariableDeclaration: 'VariableDeclaration',
  EXPRESSION_STATEMENT: 'ExpressionStatement',
  AssignmentExpression: 'AssignmentExpression',
}