module.exports = {
  PROGRAM: 'Program',
  Identifier: 'Identifier',
  IfStatement: 'IfStatement',
  NullLiteral: 'NullLiteral',
  STRING_LITERAL: 'StringLiteral',
  BooleanLiteral: 'BooleanLiteral',
  NUMERIC_LITERAL: 'NumericLiteral',
  BLOCK_STATEMENT: 'BlockStatement',
  EMPTY_STATEMENT: 'EmptyStatement',
  WhileStatement: 'WhileStatement',
  ForStatement: 'ForStatement',
  DoWhileStatement: 'DoWhileStatement',
  UnaryExpression: 'UnaryExpression',
  BINARY_EXPRESSION: 'BinaryExpression',
  LogicalExpression: 'LogicalExpression',
  VariableStatement: 'VariableStatement',
  AdditiveExpression: 'AdditiveExpression',
  VariableDeclaration: 'VariableDeclaration',
  EXPRESSION_STATEMENT: 'ExpressionStatement',
  RelationalExpression: 'RelationalExpression',
  AssignmentExpression: 'AssignmentExpression',
}